<?xml version="1.0"?>

<robot name="corona_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- arguments -->
  <xacro:arg name="robot_namespace" default="/"/>
  <xacro:arg name="realsense1_enabled" default="true"/>
  <xacro:arg name="realsense2_enabled" default="true"/>
  <xacro:arg name="realsense3_enabled" default="false"/>
  <xacro:arg name="kinect1_enabled" default="true"/>
  <xacro:arg name="ur_enabled" default="true"/>
  <xacro:arg name="gripper_enabled" default="true"/>

  <!-- components -->
  <xacro:include filename="$(find cb_description)/urdf/components/inspector_bot.urdf.xacro" />  
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find robotiq_2f_85_gripper_visualization)/urdf/robotiq_arg2f_85_model_macro.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_d415.urdf.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />  
  <xacro:include filename="$(find cb_description)/urdf/accessories/kinect_tilted_camera.urdf.xacro"/>

  <!-- ********************* -->
  <!--          ur5          -->
  <!-- ********************* -->
  <xacro:if value="$(arg ur_enabled)">
    <xacro:property name="ur5_z_location" value="${base_center_height + base_z_size/2}" />
    <xacro:property name="ur5_x_location" value="0.175" />
    
    <link name="real_base_link"/>
    <link name="real_ee_link"/>
    <link name="tcp_gripper_open"/>
    <link name="tcp_gripper_closed"/>
    <link name="uv_light_center"/>

    <joint name="ur_real_base_fixed_joint" type="fixed">
      <parent link="bare_base_link" />
      <child link="real_base_link" />
      <origin xyz="${ur5_x_location} 0.0 ${ur5_z_location}" rpy="0.0 0.0 ${M_PI/2}" />
    </joint>

    <joint name="ur_base_fixed_joint" type="fixed">
      <parent link="real_base_link" />
      <child link="base_link" />
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 -${M_PI}" />
    </joint>

    <joint name="ur_real_ee_fixed_joint" type="fixed">
      <parent link="ee_link" />
      <child link="real_ee_link" />
      <origin xyz="0.0 0.0 0.0" rpy="-${M_PI/2} 0.0 -${M_PI/2}" />
    </joint>

    <joint name="ur_tcp_fixed_joint" type="fixed">
      <parent link="real_ee_link"/>
      <child link="tcp_gripper_open"/>
      <origin xyz="0 0 0.13" rpy="0 0 0"/>
    </joint>

    <joint name="ur_gripper_closed_fixed_joint" type="fixed">
      <parent link="tcp_gripper_open"/>
      <child link="tcp_gripper_closed"/>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
    </joint>

    <joint name="ur_light_center_fixed_joint" type="fixed">
      <parent link="tcp_gripper_closed"/>
      <child link="uv_light_center"/>
      <origin xyz="-0.155 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:ur5_robot prefix="" joint_limited="false"/>

    <!-- gripper -->
    <xacro:if value="$(arg gripper_enabled)">  
      
      <joint name="ur_gripper_fixed_joint" type="fixed">
        <parent link="tool0"/>
        <child link="robotiq_arg2f_base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </joint>

      <joint name="ur_ee_fixed_joint" type="fixed">
        <parent link="tool0"/>
        <child link="robotiq_ee"/>
        <origin xyz="0 0 0.13" rpy="0 -${M_PI/2} 0"/>
      </joint>

      <link name="robotiq_ee"/>


      <xacro:robotiq_arg2f_85 prefix=""/>
    </xacro:if>
  </xacro:if>

  <!-- ********************* -->
  <!--       realsense       -->
  <!-- ********************* -->
  <xacro:if value="$(arg realsense1_enabled)">
    <link name="realsense1_base_link" />

    <joint name="realsense1_mount_fixed_joint" type="fixed">
      <parent link="ee_link"/>
      <child link="realsense1_base_link"/>
      <origin xyz="-0.02 0.065 0.0" rpy="${-M_PI/2} 0 0"/>
    </joint>

    <xacro:sensor_d415 parent="realsense1_base_link" name="realsense1">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:sensor_d415>
  </xacro:if>

  <xacro:if value="$(arg realsense2_enabled)">
    <link name="realsense2_mount_link" />
  
    <joint name="realsense2_profile_fixed_joint" type="fixed">
      <parent link="camera_profile_left"/>
      <child link="realsense2_mount_link"/>
      <origin xyz="0 0 ${profile_left_height/2}" rpy="0 0 ${M_PI/4}"/>
    </joint>

    <link name="realsense2_base_link" />
    <joint name="realsense2_mount_fixed_joint" type="fixed">
      <parent link="realsense2_mount_link"/>
      <child link="realsense2_base_link"/>
      <origin xyz="0.035 0 0.025" rpy="0 ${M_PI/6} 0"/>
    </joint>

    <xacro:sensor_d435 parent="realsense2_base_link" name="realsense2">
      <origin xyz="0.010 0 -0.0125" rpy="0 0 0"/>
    </xacro:sensor_d435>
  </xacro:if>

  <xacro:if value="$(arg realsense3_enabled)">
    <link name="realsense3_mount_link" />
  
    <joint name="realsense3_profile_fixed_joint" type="fixed">
      <parent link="camera_profile_right"/>
      <child link="realsense3_mount_link"/>
      <origin xyz="0 0 ${profile_right_height/2}" rpy="0 0 ${-M_PI/4}"/>
    </joint>

    <link name="realsense3_base_link" />
    <joint name="realsense3_mount_fixed_joint" type="fixed">
      <parent link="realsense3_mount_link"/>
      <child link="realsense3_base_link"/>
      <origin xyz="0.035 0 0.025" rpy="0 ${M_PI/6} 0"/>
    </joint>

    <xacro:sensor_d435 parent="realsense3_base_link" name="realsense3">
      <origin xyz="0.010 0 -0.0125" rpy="0 0 0"/>
    </xacro:sensor_d435>
  </xacro:if>

  <!-- ********************* -->
  <!--         kinect        -->  
  <!-- ********************* -->
  <xacro:if value="$(arg kinect1_enabled)">
    <xacro:arg name="kinect1_base_xyz" default="${base_x_size/2 + 0.041} 0 ${base_center_height + base_z_size/2 - 0.071}"/>
    <xacro:arg name="kinect1_base_rpy" default="0 0 0"/>
    <xacro:arg name="kinect1_tilt_angle" default="0"/>
  
    <xacro:kinect_tilted_camera prefix="kinect1" robot_namespace="$(arg robot_namespace)" 
      base_xyz="$(arg kinect1_base_xyz)" base_rpy="$(arg kinect1_base_rpy)" tilt_angle="$(arg kinect1_tilt_angle)"/>
  </xacro:if>

</robot>